In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("weather.csv")

In [3]:
y = dataset.iloc[:,-1]
X = dataset.iloc[:,0:-1]

In [4]:
from sklearn.preprocessing import LabelEncoder
encode_x = LabelEncoder()

In [5]:
wind_dir = X.iloc[:,5]
categorical = encode_x.fit_transform(wind_dir)
X.iloc[:,5] = categorical

In [6]:
encode_x.inverse_transform([0,1,2,3,4,5,6,7])

/usr/local/lib64/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array(['E', 'N', 'NE', 'NW', 'S', 'SE', 'SW', 'W'], dtype=object)

In [7]:
weather = y
cat = encode_x.fit_transform(weather)
y = cat

In [8]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(categorical_features=[5]) #5 is the position of data in datatset which is to be encoded
X = OHE.fit_transform(X)
X = X.toarray()      #converts X to array

In [9]:
X

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 5.0000e+01, 1.0197e+03,
        7.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 5.0000e+01, 1.0124e+03,
        5.0000e+00],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, ..., 4.5000e+01, 1.0095e+03,
        8.0000e+00],
       ...,
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 6.0000e+01, 1.0123e+03,
        1.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 7.7000e+01, 1.0157e+03,
        7.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 7.4000e+01, 1.0185e+03,
        8.0000e+00]])

In [10]:
X = X[:,1:]              

In [11]:
X[:,-2]

array([1019.7, 1012.4, 1009.5, 1005.5, 1018.3, 1023.8, 1024.6, 1026.2,
       1026.1, 1024.1, 1024.4, 1023.8, 1022. , 1017.3, 1018.2, 1017.9,
       1014.4, 1016.4, 1017.1, 1018.5, 1012.4, 1010.7, 1014. , 1020.7,
       1022.4, 1019.7, 1021. , 1019.2, 1019. , 1017.2, 1015. , 1013.9,
       1007.9, 1007.3, 1015. , 1018.8, 1014.5, 1014.8, 1010.8, 1011.7,
       1018. , 1021.1, 1021.9, 1018.1, 1012.6, 1010.1, 1017.6, 1020.6,
       1018. , 1015.8, 1012.9,  996.5, 1009.5, 1012.8, 1020.4, 1023.2,
       1017.3, 1016.8, 1017.1, 1017.4, 1019.2, 1015.8, 1012.6, 1016.8,
       1016.2, 1011.8, 1006.6, 1012.3, 1015.7, 1018.5])

In [12]:
import numpy as np

In [13]:
bias_wt = np.ones((70,1)) #create and empty column of 70 rows with value 1.This is the weight of bias
#2D array

In [14]:
X_opt = np.append(arr = bias_wt, values=X, axis = 1) 
#add X in bias array..axis0=row(bydefault) axis1=xol

In [15]:
import statsmodels.formula.api as sm

In [16]:
X_opt_feature = X_opt[: , [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]]
model_opt = sm.OLS(y,X_opt_feature).fit()  #it will tell insignificant vars. SL =5% = 0.5
model_opt.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.680
Method:                 Least Squares   F-statistic:                     10.18
Date:                Wed, 22 May 2019   Prob (F-statistic):           4.98e-11
Time:                        23:46:02   Log-Likelihood:                -51.297
No. Observations:                  70   AIC:                             136.6
Df Residuals:                      53   BIC:                             174.8
Df Model:                          16                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         43.2509     21.351      2.026      0.048       0.426      86.075
x1             0.0485      0.324      0.150      0.882      -0.602       0.699
x2            -0.7108      0.384     -1.849      0.070      -1.482       0.060
x3            -0.1500      0.270     -0.556      0.581      -0.691       0.392
x4            -0.1498      0.336     -0.446      0.657      -0.824       0.524
x5            -0.0564      0.228     -0.247      0.806      -0.514       0.402
x6            -0.4032      0.337     -1.198      0.236      -1.078       0.272
x7            -0.5202      0.486     -1.070      0.289      -1.496       0.455
x8            -0.0160      0.045     -0.357      0.723      -0.106       0.074
x9            -0.0226      0.032     -0.714      0.478      -0.086       0.041
x10            0.0713      0.015      4.897      0.000       0.042       0.101
x11           -0.0820      0.038     -2.182      0.034      -0.157      -0.007
x12            0.0113      0.030      0.373      0.710      -0.050       0.072
x13           -0.0164      0.013     -1.288      0.203      -0.042       0.009
x14            0.0009      0.009      0.101      0.920      -0.016       0.018
x15           -0.0409      0.021     -1.979      0.053      -0.082       0.001
x16            0.1418      0.039      3.681      0.001       0.065       0.219
==============================================================================
Omnibus:                        6.543   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.038   Jarque-Bera (JB):                6.192
Skew:                           0.518   Prob(JB):                       0.0452
Kurtosis:                       4.025   Cond. No.                     3.15e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.15e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [17]:
X_opt_feature = X_opt[: , [0,2,6,7,9,10,11,13,15,16]]
model_opt = sm.OLS(y,X_opt_feature).fit()  #it will tell insignificant vars. SL =5% = 0.5
model_opt.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.750
Model:                            OLS   Adj. R-squared:                  0.713
Method:                 Least Squares   F-statistic:                     20.02
Date:                Wed, 22 May 2019   Prob (F-statistic):           5.29e-15
Time:                        23:46:02   Log-Likelihood:                -51.915
No. Observations:                  70   AIC:                             123.8
Df Residuals:                      60   BIC:                             146.3
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         40.8869     16.045      2.548      0.013       8.791      72.982
x1            -0.6733      0.319     -2.112      0.039      -1.311      -0.036
x2            -0.3461      0.263     -1.317      0.193      -0.872       0.179
x3            -0.4386      0.409     -1.072      0.288      -1.257       0.380
x4            -0.0248      0.021     -1.166      0.248      -0.067       0.018
x5             0.0686      0.012      5.537      0.000       0.044       0.093
x6            -0.0843      0.032     -2.621      0.011      -0.149      -0.020
x7            -0.0142      0.011     -1.268      0.210      -0.037       0.008
x8            -0.0385      0.015     -2.497      0.015      -0.069      -0.008
x9             0.1327      0.027      4.879      0.000       0.078       0.187
==============================================================================
Omnibus:                        6.351   Durbin-Watson:                   2.040
Prob(Omnibus):                  0.042   Jarque-Bera (JB):                5.546
Skew:                           0.592   Prob(JB):                       0.0625
Kurtosis:                       3.705   Cond. No.                     2.49e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.49e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X_opt_feature, y, test_size=0.10, random_state=42)

In [20]:
model = LinearRegression()

In [21]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [22]:
y_pred = model.predict(X_test)

In [23]:
model.coef_

array([ 0.        , -0.65283892, -0.30879908, -0.45358875, -0.01787934,
        0.07504849, -0.09855445, -0.01228118, -0.03800442,  0.12489965])

In [24]:
bias = model.intercept_

In [25]:
encode_x.inverse_transform([0,1,2,3])

/usr/local/lib64/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array(['clear', 'cloudy', 'haze', 'rainy'], dtype=object)

In [26]:
y_pred

array([ 3.83761069,  1.05135942,  2.19782405,  1.43047948,  1.3484507 ,
       -0.36180322,  0.44773547])

In [27]:
y_test

array([3, 1, 3, 2, 3, 0, 0])

In [28]:
PRED = []
PRED.append(bias)

In [29]:
win_dir = input("Enter direction of wind : ")
if win_dir == 'NE':
    PRED.append(1)
    PRED.append(0)
    PRED.append(0)
elif win_dir == 'SW':
    PRED.append(0)
    PRED.append(1)
    PRED.append(0)
elif win_dir == 'W':
    PRED.append(0)
    PRED.append(0)
    PRED.append(1)
else:
    PRED.append(0)
    PRED.append(0)
    PRED.append(0)
    

Enter direction of wind : NE


In [30]:
temp = float(input("Enter Maximum Temperature : "))
PRED.append(temp)

Enter Maximum Temperature : 35


In [31]:
rain = float(input("Enter Rainfall : "))
PRED.append(rain)

Enter Rainfall : 4.2


In [32]:
evap = float(input("Enter Evaporation : "))
PRED.append(evap)

Enter Evaporation : 1.7


In [33]:
win_speed = float(input("Enter Wind Speed : "))
PRED.append(win_speed)

Enter Wind Speed : 15


In [34]:
pressure = float(input("Enter Pressure : "))
PRED.append(pressure)

Enter Pressure : 1010


In [35]:
cloud = float(input("Enter Cloud : "))
PRED.append(cloud)

Enter Cloud : 7


In [36]:
PRED = np.asarray(PRED,dtype="float")
PRED = PRED.reshape(1,-1)

In [37]:
y_p = model.predict(PRED)

In [38]:
y_p

array([1.37968088])

In [39]:
if y_p >= 2.7 :
    y_out = 'rainy. You should not go out.'
elif y_p >= 1.7 and y_p < 2.7:
    y_out = 'haze. You should carry an umbrella with you.'
elif y_p >= 0.7 and y_p < 1.7:
    y_out = 'cloudy. You may carry an umbrella.'
elif y_p >= -1:
    y_out = 'clear. Have a nice day.'

In [40]:
print(f"The weather is {y_out}")

The weather is cloudy. You may carry an umbrella.
